#!/usr/bin/env python3
"""
Job2 orchestrator: detect changed specs and generate API test-case packs via AI.

Usage:
    python3 scripts/testgen/run_generation.py \
        --manifest  data/manifests/openapi-manifest.json \
        --registry  data/registry/processed-specs.json \
        --specs-dir data/fetched \
        --output-dir data/generated/testcases \
        --provider  mock
"""
import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from common.hashing import hash_content
from common.io_utils import read_json, read_text, write_json, write_text
from testgen.detect_changed_specs import detect_changes
from testgen.prepare_ai_input import prepare_ai_input
from testgen.render_markdown import render_markdown
from testgen.update_registry import update_registry

# ---------------------------------------------------------------------------
# AI provider abstraction
# ---------------------------------------------------------------------------

class MockProvider:
    """Returns a deterministic mock response — no external calls."""

    def generate(self, system_prompt: str, user_prompt: str) -> str:  # noqa: ARG002
        return json.dumps({
            "scope_summary": (
                "Mock scope summary. This is a placeholder generated by the mock provider "
                "for pipeline testing without live AI calls."
            ),
            "assumptions": [
                "No live AI provider configured; output is mock data.",
                "Real test cases will be generated when AI_PROVIDER is set to a live provider.",
            ],
            "spec_gaps": [
                "Mock run: spec gaps not evaluated.",
            ],
            "test_cases": [
                {
                    "id": "TC-001",
                    "title": "Mock — Happy path",
                    "endpoint": "/example",
                    "method": "GET",
                    "operationId": "getExample",
                    "objective": "Verify the endpoint returns 200 for a valid request.",
                    "preconditions": "Valid credentials configured.",
                    "input": "No request body. Valid auth header.",
                    "expected_result": "HTTP 200 with valid response body matching the declared schema.",
                    "validation_points": [
                        "Response status code is 200.",
                        "Response body matches the declared schema.",
                        "Content-Type header is application/json.",
                    ],
                    "priority": "High",
                    "scenario_type": "Positive",
                    "notes": "MOCK: replace with real AI-generated output.",
                },
            ],
        })


class GithubModelsProvider:
    """
    Calls the GitHub Models API (OpenAI-compatible endpoint).

    Authentication: uses the GITHUB_TOKEN environment variable.
    Model:          controlled by GITHUB_MODELS_MODEL (default: gpt-4o).
    """

    def __init__(self, model: str = "gpt-4o", token: str = None):
        self.model = model
        self.token = token or os.environ.get("GITHUB_TOKEN", "")
        self.endpoint = "https://models.inference.ai.azure.com"

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.2,
            "response_format": {"type": "json_object"},
        }
        data = json.dumps(payload).encode()
        req = urllib.request.Request(
            f"{self.endpoint}/chat/completions",
            data=data,
            headers={
                "Authorization": f"Bearer {self.token}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                result = json.loads(resp.read())
                return result["choices"][0]["message"]["content"]
        except urllib.error.HTTPError as exc:
            body = exc.read().decode(errors="replace")
            raise RuntimeError(f"GitHub Models API {exc.code}: {body}") from exc


def _get_provider(mode: str):
    if mode in ("mock", "dry-run", ""):
        return MockProvider()
    if mode == "github-models":
        model = os.environ.get("GITHUB_MODELS_MODEL", "gpt-4o")
        return GithubModelsProvider(model=model)
    raise ValueError(f"Unknown AI_PROVIDER '{mode}'. Supported: mock, dry-run, github-models")


# ---------------------------------------------------------------------------
# Prompt helpers
# ---------------------------------------------------------------------------

def _fill_template(template: str, variables: dict) -> str:
    result = template
    for key, value in variables.items():
        result = result.replace(f"{{{{{key}}}}}", str(value))
    return result


# ---------------------------------------------------------------------------
# Per-spec processing
# ---------------------------------------------------------------------------

def _chunks(lst: list, size: int):
    for i in range(0, len(lst), size):
        yield lst[i: i + size]


def _process_spec(
    entry: dict,
    provider,
    system_prompt: str,
    user_template: str,
    specs_dir: str,
    output_dir: str,
    chunk_size: int,
) -> dict:
    service_id = entry["service_id"]
    source_path = entry["source_path"]

    spec_file = Path(specs_dir) / source_path
    if not spec_file.exists():
        return {"service_id": service_id, "success": False, "error": f"Spec file not found: {spec_file}"}

    try:
        ai_input = prepare_ai_input(str(spec_file))
    except Exception as exc:
        return {"service_id": service_id, "success": False, "error": f"Prepare AI input failed: {exc}"}

    endpoint_list = ai_input.get("endpoints", [])
    endpoint_chunks = list(_chunks(endpoint_list, chunk_size)) if endpoint_list else [[]]

    all_test_cases: list = []
    scope_summary = ""
    assumptions: list = []
    spec_gaps: list = []

    for i, ep_chunk in enumerate(endpoint_chunks):
        chunk_context = (
            f"This is chunk {i + 1} of {len(endpoint_chunks)}. "
            "Continue test-case numbering from where the previous chunk left off."
            if len(endpoint_chunks) > 1
            else ""
        )
        user_prompt = _fill_template(user_template, {
            "service_name": entry.get("display_name") or service_id,
            "spec_metadata": json.dumps(ai_input["service_metadata"], indent=2),
            "endpoint_summary": json.dumps(ep_chunk, indent=2),
            "schema_summary": json.dumps(ai_input.get("component_schema_names", []), indent=2),
            "security_summary": json.dumps(ai_input.get("security_definitions", []), indent=2),
            "chunk_context": chunk_context,
            "output_constraints": (
                "Return a JSON object with keys: scope_summary (string), "
                "assumptions (array of strings), spec_gaps (array of strings), "
                "test_cases (array of test-case objects)."
            ),
        })

        try:
            raw = provider.generate(system_prompt, user_prompt)
        except Exception as exc:
            return {"service_id": service_id, "success": False, "error": f"AI call failed (chunk {i + 1}): {exc}"}

        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            # Try extracting the first JSON object from a mixed response
            m = re.search(r"\{.*\}", raw, re.DOTALL)
            if m:
                try:
                    parsed = json.loads(m.group())
                except Exception:
                    parsed = {}
            else:
                parsed = {}

        if not parsed:
            return {"service_id": service_id, "success": False, "error": f"Unparseable AI output (chunk {i + 1})"}

        if i == 0:
            scope_summary = parsed.get("scope_summary", "")
            assumptions = parsed.get("assumptions") or []
            spec_gaps = parsed.get("spec_gaps") or []

        chunk_cases = parsed.get("test_cases") or []
        # Re-number TCs for consistency across chunks
        offset = len(all_test_cases)
        for j, tc in enumerate(chunk_cases):
            tc["id"] = f"TC-{offset + j + 1:03d}"
        all_test_cases.extend(chunk_cases)

    markdown = render_markdown(
        entry=entry,
        scope_summary=scope_summary,
        assumptions=assumptions,
        spec_gaps=spec_gaps,
        test_cases=all_test_cases,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )

    output_file = Path(output_dir) / f"{service_id}-testcases.md"
    write_text(str(output_file), markdown)
    out_hash = hash_content(markdown)

    print(f"  Generated: {output_file.name} ({len(all_test_cases)} test case(s))")
    return {
        "service_id": service_id,
        "success": True,
        "output_path": str(output_file),
        "output_hash": out_hash,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate API test-case packs from OpenAPI specs")
    parser.add_argument("--manifest", default="data/manifests/openapi-manifest.json")
    parser.add_argument("--registry", default="data/registry/processed-specs.json")
    parser.add_argument("--specs-dir", default="data/fetched",
                        help="Directory containing the normalized spec files")
    parser.add_argument("--output-dir", default="data/generated/testcases")
    parser.add_argument("--system-prompt", default="prompts/system/api-testcases-system.md")
    parser.add_argument("--user-template", default="prompts/templates/api-testcases-user.md")
    parser.add_argument("--provider", default=None,
                        help="AI provider mode (overrides AI_PROVIDER env var)")
    parser.add_argument("--force-all", action="store_true",
                        help="Process all specs, ignoring the registry")
    parser.add_argument("--chunk-size", type=int, default=50,
                        help="Max endpoints per AI call chunk")
    args = parser.parse_args()

    provider_mode = args.provider or os.environ.get("AI_PROVIDER", "mock")
    print(f"AI provider: {provider_mode}")

    provider = _get_provider(provider_mode)
    system_prompt = read_text(args.system_prompt)
    user_template = read_text(args.user_template)

    Path(args.output_dir).mkdir(parents=True, exist_ok=True)

    try:
        registry = read_json(args.registry)
    except FileNotFoundError:
        registry = {"specs": {}}

    classification = detect_changes(args.manifest, args.registry)

    manifest = read_json(args.manifest)
    all_specs = manifest.get("specs", [])
    to_process = all_specs if args.force_all else (classification["new"] + classification["changed"])

    total = len(all_specs)
    skip_count = len(classification["unchanged"])
    print(
        f"\nSpecs: total={total}  new={len(classification['new'])}  "
        f"changed={len(classification['changed'])}  unchanged={skip_count}"
    )
    print(f"Processing: {len(to_process)} spec(s)\n")

    success_count = 0
    fail_count = 0

    for entry in to_process:
        print(f"→ {entry['service_id']} ({entry['source_path']})")
        result = _process_spec(
            entry=entry,
            provider=provider,
            system_prompt=system_prompt,
            user_template=user_template,
            specs_dir=args.specs_dir,
            output_dir=args.output_dir,
            chunk_size=args.chunk_size,
        )

        if result["success"]:
            success_count += 1
            update_registry(
                registry=registry,
                service_id=entry["service_id"],
                source_path=entry["source_path"],
                spec_hash=entry["spec_hash"],
                output_file=result["output_path"],
                output_hash=result["output_hash"],
                status="success",
            )
        else:
            fail_count += 1
            err = result.get("error", "unknown error")
            print(f"  FAILED: {err}", file=sys.stderr)
            update_registry(
                registry=registry,
                service_id=entry["service_id"],
                source_path=entry["source_path"],
                spec_hash=entry["spec_hash"],
                output_file="",
                output_hash="",
                status="failed",
                notes=err,
            )

    write_json(args.registry, registry)

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "ai_provider": provider_mode,
        "total_specs": total,
        "new": len(classification["new"]),
        "changed": len(classification["changed"]),
        "unchanged": skip_count,
        "processed": len(to_process),
        "generated": success_count,
        "failed": fail_count,
    }

    print("\n--- Summary ---")
    for k, v in report.items():
        print(f"  {k}: {v}")

    write_json(f"{args.output_dir}/generation-report.json", report)

    if fail_count > 0:
        print(f"\n{fail_count} spec(s) failed. See errors above.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
